apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP
      #port in the service
      port: 80
      #port in the container
      targetPort: 8080
    # - protocol: TCP
    #   port: 443
    #   targetPort: 8080
  type: LoadBalancer
